name = 'Schematicae'
license = 'MIT'
licenselink = 'https://github.com/uZer/schematicae/LICENSE'
description = 'ypiolet.fr theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/uZer/schematicae'

# If you have a running demo of the theme
demosite = 'https://hub.ypiolet.fr'

# Taxonomy terms
tags = ['blog', 'personnal', 'projects', 'artist']
features = ['some', 'awesome', 'features']

[author]
name = 'Youenn'
homepage = 'https://ypiolet.fr'
